---
- name: This is a hello-world example
  hosts: localhost
  become: true
  become_method: sudo 
  tasks:
    - name: docker_inspect
      docker_inspect:
    - name: set_fact for container_id
      set_fact:
          container: "{{ container | default('f96751168a19') }}" 
    - name: Run docker command to get list of pkgs installed
      command: "docker exec {{ container }} echo \"Hello from container!\" "
      register: testvar
    - name: debug
      debug:
        msg: "{{ testvar }}"
    - name: Run command for list of rpm packages installed
      command: "docker exec {{ container }} rpm -qa"
      register: package_list
    - name: debug
      debug:
        msg: "{{ package_list }}"
    - name: info of each package
      command: "docker exec {{ container }} rpm -qi {{ item }}"
      with_items: "{{ package_list['stdout_lines'] }}"
      register: dep_output
    - name: All rpms information formatted
      debug: 
        msg: "{{ dep_output | format_pkg_output | get_build_info | length }}"
    - name: All rpms info just the build info
      set_fact: 
        rpm_info: "{{ dep_output | format_pkg_output | get_build_info | get_build_from_koji }}"
    - copy: 
        content: "{{ rpm_info | to_nice_json }}" 
        dest: ./pkgout_json.txt
    - copy:
        content: "{{ rpm_info | to_nice_yaml }}"
        dest: ./pkgout_yaml.txt
    - name: "All dependencies"
      debug:
    - name: "Which dependency needs what"
      debug:
    - name: "Need overlapping dependencies"
      debug:
